services:
  Movvi-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Movvi-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword!123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - Movvi-network

  Movvi-api:
    container_name: Movvi-api
    build:
      context: .
      dockerfile: Movvi.ApiService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__DefaultConnection: >
        Server=Movvi-sqlserver,1433;
        Database=MovviDb;
        User Id=sa;
        Password=StrongPassword!123;
        TrustServerCertificate=True;
    depends_on:
      - Movvi-sqlserver
    networks:
      - Movvi-network

  Movvi-web:
    container_name: Movvi-web
    build:
      context: .
      dockerfile: Movvi.Web/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Api__BaseUrl: http://Movvi-api:8080
    depends_on:
      - Movvi-api
    networks:
      - Movvi-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

networks:
  Movvi-network:
    driver: bridge

volumes:
  sqlserver-data:
